/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitInput(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    /* Code for StartInput Goes Here */
    visitListJob(p->u.startinput_.listjob_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void visitJob(Job p)
{
  switch(p->kind)
  {
  case is_OneJobFG:
    /* Code for OneJobFG Goes Here */
    visitCommandLine(p->u.onejobfg_.commandline_);
    break;
  case is_OneJobBG:
    /* Code for OneJobBG Goes Here */
    visitCommandLine(p->u.onejobbg_.commandline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Job!\n");
    exit(1);
  }
}

void visitListJob(ListJob p)
{
  switch(p->kind)
  {
  case is_SeparatorJob:
    /* Code for SeparatorJob Goes Here */
    visitJob(p->u.separatorjob_.job_);
    visitListJob(p->u.separatorjob_.listjob_);
    break;
  case is_ConsJob:
    /* Code for ConsJob Goes Here */
    visitJob(p->u.consjob_.job_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ListJob!\n");
    exit(1);
  }
}

void visitCommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    /* Code for MkCmdLine Goes Here */
    visitPipeline(p->u.mkcmdline_.pipeline_);
    visitOptRedir(p->u.mkcmdline_.optredir_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandLine!\n");
    exit(1);
  }
}

void visitOptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:
    /* Code for NoRedir Goes Here */
    break;
  case is_InOutRedir:
    /* Code for InOutRedir Goes Here */
    visitWord(p->u.inoutredir_.word_1);
    visitWord(p->u.inoutredir_.word_2);
    break;
  case is_OutInRedir:
    /* Code for OutInRedir Goes Here */
    visitWord(p->u.outinredir_.word_1);
    visitWord(p->u.outinredir_.word_2);
    break;
  case is_OutRedir:
    /* Code for OutRedir Goes Here */
    visitWord(p->u.outredir_.word_);
    break;
  case is_InRedir:
    /* Code for InRedir Goes Here */
    visitWord(p->u.inredir_.word_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptRedir!\n");
    exit(1);
  }
}

void visitPipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    /* Code for Single Goes Here */
    visitCommandPart(p->u.single_.commandpart_);
    break;
  case is_Pipe:
    /* Code for Pipe Goes Here */
    visitCommandPart(p->u.pipe_.commandpart_);
    visitPipeline(p->u.pipe_.pipeline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Pipeline!\n");
    exit(1);
  }
}

void visitCommandPart(CommandPart p)
{
  switch(p->kind)
  {
  case is_Cmd:
    /* Code for Cmd Goes Here */
    visitWord(p->u.cmd_.word_);
    break;
  case is_CmdWithArgs:
    /* Code for CmdWithArgs Goes Here */
    visitWord(p->u.cmdwithargs_.word_);
    visitListWordComponent(p->u.cmdwithargs_.listwordcomponent_);
    break;
  case is_CmdAssign:
    /* Code for CmdAssign Goes Here */
    visitWord(p->u.cmdassign_.word_1);
    visitWord(p->u.cmdassign_.word_2);
    break;
  case is_VarExpand:
    /* Code for VarExpand Goes Here */
    visitWord(p->u.varexpand_.word_);
    break;
  case is_IfCmd:
    /* Code for IfCmd Goes Here */
    visitPipeline(p->u.ifcmd_.pipeline_);
    visitListCommandLine(p->u.ifcmd_.listcommandline_);
    break;
  case is_IfElseCmd:
    /* Code for IfElseCmd Goes Here */
    visitPipeline(p->u.ifelsecmd_.pipeline_);
    visitListCommandLine(p->u.ifelsecmd_.listcommandline_1);
    visitListCommandLine(p->u.ifelsecmd_.listcommandline_2);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandPart!\n");
    exit(1);
  }
}

void visitWordComponent(WordComponent p)
{
  switch(p->kind)
  {
  case is_LitWord:
    /* Code for LitWord Goes Here */
    visitWord(p->u.litword_.word_);
    break;
  case is_VarWord:
    /* Code for VarWord Goes Here */
    visitWord(p->u.varword_.word_);
    break;
  case is_SubCmd:
    /* Code for SubCmd Goes Here */
    visitPipeline(p->u.subcmd_.pipeline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing WordComponent!\n");
    exit(1);
  }
}

void visitListWordComponent(ListWordComponent p)
{
  switch(p->kind)
  {
  case is_SingleWordComponent:
    /* Code for SingleWordComponent Goes Here */
    visitWordComponent(p->u.singlewordcomponent_.wordcomponent_);
    break;
  case is_ConsWordComponent:
    /* Code for ConsWordComponent Goes Here */
    visitWordComponent(p->u.conswordcomponent_.wordcomponent_);
    visitListWordComponent(p->u.conswordcomponent_.listwordcomponent_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ListWordComponent!\n");
    exit(1);
  }
}

void visitListCommandLine(ListCommandLine p)
{
  switch(p->kind)
  {
  case is_ConsCmdLine:
    /* Code for ConsCmdLine Goes Here */
    visitCommandLine(p->u.conscmdline_.commandline_);
    visitListCommandLine(p->u.conscmdline_.listcommandline_);
    break;
  case is_NilCmdLine:
    /* Code for NilCmdLine Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ListCommandLine!\n");
    exit(1);
  }
}

void visitWord(Word p)
{
  /* Code for Word Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

